### ISSUE TITLE
Improvement: don't mount source code in compose QA containers

### ISSUE THREAD

**Issue by lower29** [JiscRDSS/rdss-archivematica#127]
It's been suggested by @sevein that some of the volume mounts in our Docker Compose configuration aren't necessary for QA deployments. The affected volume mounts are for source code folders - originally intended to enable "hot" changes to be deployed during development.

For example:

```
  archivematica-mcp-server:
    image: '${REGISTRY}archivematica-mcp-server:${AM_MCPSERVER_VERSION}'
    environment: {...}
    volumes:
      - "${VOL_BASE}/../src/archivematica/src/archivematicaCommon/:/src/archivematicaCommon/"
      - "${VOL_BASE}/../src/archivematica/src/dashboard/:/src/dashboard/"
      - "${VOL_BASE}/../src/archivematica/src/MCPServer/:/src/MCPServer/"
      - "archivematica_pipeline_data:/var/archivematica/sharedDirectory:rw"
```

The first three of these volumes are not required for QA deployment, only development.

Since there is no reason why development changes should be made in a QA environment, these volume mounts can and should be removed from the QA compose config.
